# Railway deployment configuration for Green CDN
# Each service will be deployed separately on Railway
version: '3.8'

services:
  # Main Weight Manager (Primary service)
  weight-manager:
    build:
      context: .
      dockerfile: Dockerfile.manager
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=5000
      - DATAPLANE_HOST=haproxy-production.up.railway.app
      - RAILWAY_STATIC_URL=https://greencdn-manager-production.up.railway.app
    ports:
      - "5000:5000"

  # Weight Viewer
  weight-viewer:
    build:
      context: .
      dockerfile: Dockerfile.viewer
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=5001
      - DATAPLANE_HOST=haproxy-production.up.railway.app
    ports:
      - "5001:5001"

  # HAProxy Load Balancer
  haproxy:
    image: "haproxytech/haproxy-ubuntu:2.5"
    volumes:
      - "./haproxy:/usr/local/etc/haproxy/"
    environment:
      - PORT=80
    ports:
      - "80:80"
      - "5555:5555"
      - "8404:8404"

  # Echo Servers (simplified for demo)
  web1:
    image: ealen/echo-server
    environment:
      - ECHO_SERVER_TEXT=Hello from US West (California) - Low Carbon Server
      - PORT=8001
    ports:
      - "8001:80"

  web2:
    image: ealen/echo-server
    environment:
      - ECHO_SERVER_TEXT=Hello from US Central (Texas) - Moderate Carbon Server
      - PORT=8002
    ports:
      - "8002:80"

  web3:
    image: ealen/echo-server
    environment:
      - ECHO_SERVER_TEXT=Hello from US East (Mid-Atlantic) - Higher Carbon Server
      - PORT=8003
    ports:
      - "8003:80"
